# Generated by Django 5.2 on 2025-04-28 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_start', models.DateTimeField()),
                ('movie_end', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('movie_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movieschedule')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.seat')),
            ],
            options={
                'unique_together': {('seat', 'movie_schedule')},
            },
        ),
    ]
